### ISSUE TITLE
Broken Installer Link

### ISSUE THREAD

**Issue by nhanson2** [cubert-hyperspectral/cuvis.python#22]
The link to the C-Installer from the Markdown page leads to 404 error on Nexcloud.

https://cloud.cubert-gmbh.de/index.php/s/m1WfR66TjcGl96z

![image](https://github.com/cubert-hyperspectral/cuvis.python/assets/34529865/ad0e7716-68ae-4155-bf1f-171e5ec13e50)

**Comment by BenMGeo** [comment]
should be fixed.
