### ISSUE TITLE
EX04_changeDistance.py mesu.distance doesn't work

### ISSUE THREAD

**Issue by griesoss** [cubert-hyperspectral/cuvis.python#27]
In line 64 and 67 the example tries to print the original and the new distance with: `print(mesu.distance)`

However "mesu" the Measurement object doesn't seem to have an attribute called distance. Is there another way to get the distance calibration information?

**Comment by birkholz-cubert** [comment]
Hello,

thanks for pointing this out, this was indeed missing in the current wrapper implementation.
I added it back in.
You can either pull the changes from the release 3.2 branch or extract the distance yourself using the python interface layer:

`def get_distance(mesu: cuvis.Measurement):
    import cuvis_il
    _metaData = cuvis_il.cuvis_mesu_metadata_allocate()
    if cuvis_il.status_ok != cuvis_il.cuvis_measurement_get_metadata(
            mesu._handle, _metaData):
        raise cuvis.SDKException
    distance = _metaData.distance
    cuvis_il.cuvis_mesu_metadata_free(_metaData)
    return distance`
(the line for importing the `cuvis_il` module may be slightly different depending on your system)

If you have any further questions please let me know.
