### ISSUE TITLE
Error when reading calibration info

### ISSUE THREAD

**Issue by kosalk** [cubert-hyperspectral/cuvis.python#37]
When trying to read the calibration info with `calibration.get_info()`, an error is raised _AttributeError: 'Calibration' object has no attribute 'model_name'_.

In Calibration.py (line 42 to 48), the attributes should be taken from _info_ and not `self`.

**Comment by birkholz-cubert** [comment]
Hello,

thanks for pointing this mistake out. I fixed it in the wrapper implementation.
