### ISSUE TITLE
Unhandled exception when initializing an AcquisitionContext object

### ISSUE THREAD

**Issue by kosalk** [cubert-hyperspectral/cuvis.python#38]
Cuvis version: _CUBERT SDK v. 3.3.0 build: 6e3299618350f9e10837a7a39f40e810db3a753c_ (Ubuntu 22.04-amd64-nocuda)

I'm trying to run the following code (as per _EX05_recordSingleImages.py_) :
```
calibration = cuvis.Calibration(factoryDir)
processingContext = cuvis.ProcessingContext(calibration)
acquisitionContext = cuvis.AcquisitionContext(calibration)
```
and got this error:
```
ERROR:root:unhandled exception in funciton: cuvis_acq_cont_create_from_calib
NoneType: None
Exception ignored in: <function AcquisitionContext.__del__ at 0x74d727d004a0>
Traceback (most recent call last):
  File "xxx/miniforge3/envs/xxx/lib/python3.12/site-packages/cuvis/AcquisitionContext.py", line 532, in __del__
    cuvis_il.p_int_assign(_ptr, self._handle)
  File "xxx/miniforge3/envs/xxx/lib/python3.12/site-packages/cuvis_il/cuvis_il.py", line 102, in p_int_assign
    return _cuvis_pyil.p_int_assign(obj, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: in method 'p_int_assign', argument 2 of type 'int'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xxx/miniforge3/envs/xxx/lib/python3.12/site-packages/cuvis/AcquisitionContext.py", line 28, in __init__
    raise SDKException()
cuvis.cuvis_aux.SDKException: unhandled exception in funciton: cuvis_acq_cont_create_from_calib
```

I don't have the camera attached to my computer (it's being used in another project). But in _EX05_recordSingleImages.py_, the acquisition context is initialized before checking the state of the camera so it shouldn't matter whether the camera is present or not at this point.

The same error is raised even if I run:
`acquisitionContext = cuvis.AcquisitionContext(calibration, simulate=True)`
 Obviously, the argument _simulate_ doesn't apply when initializing the acquisition context from a Calibration object.

**Comment by birkholz-cubert** [comment]
Closing this as it seems to be An issue with your respective Camera (or your used Calibration File) and not the SDK. Please consider contacting http://support.cubert-hyperspectral.com/. If this issue seems to persist, feel free to reopen this issue.
