### ISSUE TITLE
Manually setting the distance leads to SDKException: Offsets generation for pan-sensor not supported

### ISSUE THREAD

**Issue by domthom21** [cubert-hyperspectral/cuvis.python#43]
I have taken a lot of Ultris X20P images from a close distance, which I measured manually.

Setting the distance with
```
procC.calc_distance(distance) # e.g. 2000 [mm]
procC.apply(m_refl)
```
leads to `SDKException: Offsets generation for pan-sensor not supported.`. 

However, I also get this error if I took an image without the pan sensor.
In general, I would like to force a recalcutation and ignore the panimage with a parameter.

Now I cannot reprocess all my data, but I cannot also not retake the images. Are there any workarounds?

**Comment by BenMGeo** [comment]
Dear @domthom21 
Your request is more related to the camera behaviour. Please, for this kind of issues, open a request at our customer portal:

http://support.cubert-hyperspectral.com/

Nevertheless:
With a pan camera, you CANNOT force a given distance to the images. The angle needs to be calculated "freshly" as the mounting might have altered angles while usage.
The pan is defined in the init file. You will be able to do that if you use a X20 non pan factory file, that we can provide on request.

When you open an issue there, we will guide you through it.

Best,
Ben
on behalf of 
Cubert Customer Service

**Comment by domthom21** [comment]
Hi Ben, thank you that was helpful. I will do.

From the framework side, I'd like to have support in the future to do recalculation for other distances while ignoring the pan image completely.

Best,
Dominik

**Comment by BenMGeo** [comment]
You are doing everything completely right to achieve what you plan for, besides the wrong init. 
Be aware, that in-SDK pan sharpening is not possible after manual distance calibration of the hyperspectral camera.
