### ISSUE TITLE
"OverflowError: Python int too large to convert to C long" when loading session file

### ISSUE THREAD

**Issue by nhanson2** [cubert-hyperspectral/cuvis.python#46]
When loading a session file to access a measurement by index, an error is raised:

The stack trace falls back to this line: 
```
self.factory_calibration = base_datetime + datetime.timedelta(milliseconds=_metaData.factory_calibration)
```
https://github.com/cubert-hyperspectral/cuvis.python/blob/96d848061a8732bd85f310a5b43b6033eb53f23a/cuvis/Measurement.py#L64

SDK Version: 3.3.0
Platform: Ubuntu 20.04

**Comment by birkholz-cubert** [comment]
Seems to be connected to faulty configured init files. Add handling for now.
